services:
  prometheus:
    labels:
      com.trunkstarter.appinfo.deprecated: "false"
      com.trunkstarter.appinfo.description: Prometheus is a systems and service monitoring system.
      com.trunkstarter.appinfo.nicename: Prometheus
      com.trunkstarter.appvars.prometheus_enabled: "false"
      com.trunkstarter.appvars.prometheus_network_mode: ""
      com.trunkstarter.appvars.prometheus_port_9090: "9090"
      com.trunkstarter.appvars.prometheus_restart: unless-stopped
